# Site settings
title: 墨客技术笔记
email: it@mkmd.cn
description: "IT互联网干货汇总"
baseurl: ""
url: "http://mkmd.cn"
twitter_username: liulantao
github_username:  Lax

permalink: pretty

comment_uyan_uid: 1936498
releated_posts_limit: 6
google_analytics_tracking_id: UA-1658815-7
google_analytics_tracking_name: mkmd.cn

beian_id: 京ICP备07014825号-2

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
exclude:
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - vendor
  - _crawler
  - _raw
  - _site
